_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
batch_size:
    value: 5000
batching:
    value: true
binary_operators:
    value:
        - +
        - '-'
        - '*'
        - /
custom_unary_operators:
    value:
        safe_log(x): log(abs(x) + 1e-5)
        safe_sqrt(x): sqrt(abs(x))
deterministic:
    value: true
gaussian_filter_sigma:
    value: 2
input_features:
    value: 17
loss:
    value: loss(x, y) = (x - y)^2 + 0.01 * abs(x)
maxsize:
    value: 40
model:
    value: PySR
model_selection:
    value: best
multithreading:
    value: false
niterations:
    value: 1000
procs:
    value: 0
random_state:
    value: 42
task:
    value: Differential Equation Discovery
testing_samples:
    value: 188
training_samples:
    value: 173
unary_operators:
    value:
        - sin
        - cos
        - sqrt
        - log
        - square
        - tanh
        - exp
        - abs
        - sign
        - safe_log
        - safe_sqrt
verbosity:
    value: 1
