name: cab
channels:
  - defaults
  - conda-forge
  - pypi
dependencies:
  - python=3.10.16
  - pip=25.0
  - numpy=2.2.4
  - numpy-base=2.2.4
  - pandas=2.2.3
  - scipy=1.15.2
  - matplotlib=3.10.1
  - sympy=1.13.3
  - scikit-learn=1.6.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - intel-openmp=2023.1.0
  - tbb=2021.8.0
  - blas=1.0
  - libffi=3.4.4
  - openssl=3.0.16
  - ca-certificates=2025.2.25
  - sqlite=3.45.3
  - tk=8.6.14
  - xz=5.6.4
  - zlib=1.2.13y
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - bzip2=1.0.8
  - setuptools=72.1.0
  - wheel=0.45.1
  - pip:
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - filelock==3.18.0
      - fonttools==4.56.0
      - joblib==1.4.2
      - juliacall==0.9.24
      - juliapkg==0.1.16
      - kiwisolver==1.4.8
      - mpmath==1.3.0
      - packaging==24.2
      - pillow==11.1.0
      - pyparsing==3.2.3
      - pysr==1.5.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - semver==3.0.4
      - six==1.17.0
      - threadpoolctl==3.6.0
      - tzdata==2025.2
