_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
batch_size:
    value: 2000
batching:
    value: true
binary_operators:
    value:
        - +
        - '-'
        - '*'
        - /
model:
    value: PySR
niterations:
    value: 15000
task:
    value: Differential Equation Discovery
unary_operators:
    value:
        - sin
        - cos
        - exp
        - log
        - sqrt
        - abs
        - square
        - tan
