_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
batch_size:
    value: 3
batching:
    value: true
binary_operators:
    value:
        - +
        - '-'
        - '*'
        - /
complexity_of_operators:
    value:
        /: 5
        cos: 2
        sin: 2
        square: 2
        tanh: 3
deterministic:
    value: true
loss:
    value: loss(x, y) = (x - y)^2 + 0.01 * abs(x)
maxsize:
    value: 30
model:
    value: PySR
model_selection:
    value: best
niterations:
    value: 3
parallelism:
    value: serial
procs:
    value: 0
random_state:
    value: 42
should_simplify:
    value: false
task:
    value: Differential Equation Discovery
unary_operators:
    value:
        - sin
        - cos
        - abs
        - square
        - tanh
verbosity:
    value: 1
