_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 3
                - 5
            "12": 0.19.9
            "13": windows-amd64
batch_size:
    value: 3000
batching:
    value: true
binary_operators:
    value:
        - +
        - '-'
        - '*'
        - /
custom_unary_operators:
    value:
        safe_log(x): log(abs(x) + 1e-5)
        safe_sqrt(x): sqrt(abs(x))
        square(x): x^2
deterministic:
    value: false
model:
    value: PySR
multithreading:
    value: true
niterations:
    value: 1000
procs:
    value: 10
random_state:
    value: 42
task:
    value: Differential Equation Discovery
unary_operators:
    value:
        - sin
        - cos
        - exp
        - safe_log
        - safe_sqrt
        - abs
        - square
