_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 5000
batching:
    value: true
binary_operators:
    value:
        - +
        - '-'
        - '*'
        - div
constraints:
    value:
        /:
            - 3
            - 2
        exp: 1
denoise:
    value: true
deterministic:
    value: true
loss:
    value: L2DistLoss() + 0.1*L1DistLoss()
maxsize:
    value: 25
model:
    value: PySR
model_selection:
    value: accuracy
nested_constraints:
    value:
        exp: 0
        tanh: 0
niterations:
    value: 50
optimizer:
    value:
        algorithm: Nelder-Mead
        restarts: 2
procs:
    value: 0
random_state:
    value: 42
simplify:
    value: true
task:
    value: Damped Catenary Dynamics
unary_operators:
    value:
        - square
        - tanh
        - neg
        - exp
verbosity:
    value: 1
warmup:
    value: true
