_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 13
                - 15
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
LAGRANGIAN_MODE:
    value: split
binary_operators:
    value:
        - +
        - '-'
        - '*'
        - /
complexity_of_operators:
    value:
        '*': 2
        +: 1
        '-': 1
        /: 5
loss:
    value: loss(x, y) = (x - y)^2
maxsize:
    value: 30
model:
    value: PySR
niterations:
    value: 1000
procs:
    value: 0
random_state:
    value: 42
task:
    value: Lagrangian Discovery
unary_operators:
    value:
        - sin
        - cos
        - abs
        - square
        - tanh
verbosity:
    value: 1
